apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c97rt18eo-nodejs 
  janus-idp.io/tekton: c97rt18eo-nodejs
  backstage.io/kubernetes-id: c97rt18eo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c97rt18eo-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml