apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c97rt18eo-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:5ed60672248f57382c8a6e4ab9fb2b3d84b4ed60@sha256:52e4fb48a44b85fe93304b6ad6af6636f5aa0f007e192862330b5623c0dea6f0
          name: container-image
